openapi: 3.0.0
info: 
  title: Documentation
  description: How we can writr the documentation of an application
  version: 1.0.1
  contact:
    email: "abhii5496@gmail.com"
    url: "abhii5496.netlify.app"

servers:
  - url: "{protocol}://localhost:5000/api/{version}"
    description: for localhost
    variables: 
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
        - http
        - https
        default: http
      

components: 
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /abhi:
    get:
      tags:
        - String
      summary: returns a greet message from abhi
      responses: 
        200:
          description: all good and success
          content:
            application/json:
              schema:
                type: string
                example: "mystring"
        400:
          description: bad request
        500:
          description: internal sever error
